import { mkdtemp, readFile, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { JsonStateStore, pruneStateByTtl } from "../src/core/state-store.js";

describe("JsonStateStore", () => {
  it("returns empty state when file does not exist", async () => {
    const tmpDir = await mkdtemp(path.join(os.tmpdir(), "codefox-state-"));
    const store = new JsonStateStore(path.join(tmpDir, "missing.json"));

    const loaded = await store.load();
    expect(loaded.sessions).toEqual([]);
    expect(loaded.approvals).toEqual([]);
    expect(loaded.specWorkflows).toEqual([]);
  });

  it("saves and reloads sessions/approvals/specWorkflows", async () => {
    const tmpDir = await mkdtemp(path.join(os.tmpdir(), "codefox-state-"));
    const statePath = path.join(tmpDir, "state.json");
    const store = new JsonStateStore(statePath);

    await store.save({
      sessions: [
        {
          chatId: 100,
          mode: "active",
          selectedRepo: "payments-api",
          activeRequestId: "abc",
          codexThreadId: "thread_1",
          codexLastActiveAt: new Date().toISOString(),
          updatedAt: new Date().toISOString()
        }
      ],
      approvals: [
        {
          id: "req-1",
          chatId: 100,
          userId: 1,
          repoName: "payments-api",
          mode: "active",
          instruction: "fix tests",
          capabilityRef: "repo.prepare_branch",
          createdAt: new Date().toISOString()
        }
      ],
      specWorkflows: [
        {
          chatId: 100,
          workflow: {
            revisions: [
              {
                version: 1,
                stage: "interpreted",
                status: "draft",
                sourceIntent: "fix tests",
                createdAt: new Date().toISOString(),
                updatedAt: new Date().toISOString(),
                sections: {
                  REQUEST: "fix tests",
                  GOAL: "Implement and validate fix tests",
                  OUTCOME: "Tests are green",
                  CONSTRAINTS: ["No unrelated refactors"],
                  NON_GOALS: ["No infra changes"],
                  CONTEXT: ["Generated by draft"],
                  ASSUMPTIONS: ["Standard toolchain available"],
                  QUESTIONS: ["Any release constraints?"],
                  PLAN: ["Run tests", "Fix failures", "Re-run tests"],
                  APPROVALS_REQUIRED: ["Before destructive changes"],
                  DONE_WHEN: ["Requested test failures are resolved"]
                }
              }
            ]
          }
        }
      ]
    });

    const loaded = await store.load();
    expect(loaded.sessions.length).toBe(1);
    expect(loaded.approvals.length).toBe(1);
    expect(loaded.approvals[0]?.capabilityRef).toBe("repo.prepare_branch");
    expect(loaded.specWorkflows.length).toBe(1);
    expect(loaded.sessions[0].selectedRepo).toBe("payments-api");
    expect(loaded.sessions[0].codexThreadId).toBe("thread_1");
    expect(loaded.specWorkflows[0]?.workflow.revisions[0]?.sections.REQUEST).toBe("fix tests");
    expect(typeof loaded.sessions[0].updatedAt).toBe("string");

    const raw = await readFile(statePath, "utf8");
    expect(raw).toContain("payments-api");
    expect(raw).toContain("specWorkflows");
  });

  it("sanitizes malformed state on load", async () => {
    const tmpDir = await mkdtemp(path.join(os.tmpdir(), "codefox-state-"));
    const statePath = path.join(tmpDir, "state.json");
    await writeFile(
      statePath,
      JSON.stringify({
        sessions: [{ chatId: "bad", mode: "active" }, { chatId: 1, mode: "observe", codexThreadId: 2 }],
        approvals: [
          { id: "x", chatId: "bad", capabilityRef: "bad ref" },
          {
            id: "valid",
            chatId: 1,
            userId: 2,
            repoName: "payments-api",
            mode: "active",
            instruction: "do thing",
            capabilityRef: "bad ref",
            createdAt: "2026-01-01T00:00:00.000Z"
          }
        ],
        specWorkflows: [{ chatId: "bad", workflow: {} }]
      }),
      "utf8"
    );

    const store = new JsonStateStore(statePath);
    const loaded = await store.load();

    expect(loaded.sessions).toEqual([
      {
        chatId: 1,
        mode: "observe",
        selectedRepo: undefined,
        activeRequestId: undefined,
        codexThreadId: undefined,
        codexLastActiveAt: undefined,
        reasoningEffortOverride: undefined,
        updatedAt: expect.any(String)
      }
    ]);
    expect(loaded.approvals).toEqual([
      {
        id: "valid",
        chatId: 1,
        userId: 2,
        repoName: "payments-api",
        mode: "active",
        instruction: "do thing",
        capabilityRef: undefined,
        createdAt: "2026-01-01T00:00:00.000Z"
      }
    ]);
    expect(loaded.specWorkflows).toEqual([]);
  });

  it("prunes stale sessions and approvals when TTL is set", () => {
    const now = new Date("2026-01-02T12:00:00.000Z");
    const result = pruneStateByTtl(
      {
        sessions: [
          {
            chatId: 100,
            mode: "active",
            updatedAt: "2026-01-02T11:30:00.000Z"
          },
          {
            chatId: 200,
            mode: "active",
            updatedAt: "2026-01-01T00:00:00.000Z"
          }
        ],
        approvals: [
          {
            id: "fresh",
            chatId: 100,
            userId: 1,
            repoName: "payments-api",
            mode: "active",
            instruction: "fix tests",
            createdAt: "2026-01-02T11:45:00.000Z"
          },
          {
            id: "stale",
            chatId: 200,
            userId: 1,
            repoName: "payments-api",
            mode: "active",
            instruction: "fix tests",
            createdAt: "2025-12-30T11:45:00.000Z"
          }
        ],
        specWorkflows: [
          {
            chatId: 100,
            workflow: {
              revisions: [
                {
                  version: 1,
                  stage: "interpreted",
                  status: "draft",
                  sourceIntent: "fix tests",
                  createdAt: "2026-01-02T11:30:00.000Z",
                  updatedAt: "2026-01-02T11:30:00.000Z",
                  sections: {
                    REQUEST: "fix tests",
                    GOAL: "goal",
                    OUTCOME: "outcome",
                    CONSTRAINTS: [],
                    NON_GOALS: [],
                    CONTEXT: [],
                    ASSUMPTIONS: [],
                    QUESTIONS: [],
                    PLAN: ["plan"],
                    APPROVALS_REQUIRED: [],
                    DONE_WHEN: ["done"]
                  }
                }
              ]
            }
          },
          {
            chatId: 200,
            workflow: {
              revisions: [
                {
                  version: 1,
                  stage: "interpreted",
                  status: "draft",
                  sourceIntent: "stale",
                  createdAt: "2026-01-01T00:00:00.000Z",
                  updatedAt: "2026-01-01T00:00:00.000Z",
                  sections: {
                    REQUEST: "stale",
                    GOAL: "goal",
                    OUTCOME: "outcome",
                    CONSTRAINTS: [],
                    NON_GOALS: [],
                    CONTEXT: [],
                    ASSUMPTIONS: [],
                    QUESTIONS: [],
                    PLAN: ["plan"],
                    APPROVALS_REQUIRED: [],
                    DONE_WHEN: ["done"]
                  }
                }
              ]
            }
          }
        ]
      },
      {
        sessionTtlHours: 2,
        approvalTtlHours: 24
      },
      now
    );

    expect(result.state.sessions.map((session) => session.chatId)).toEqual([100]);
    expect(result.state.approvals.map((approval) => approval.id)).toEqual(["fresh"]);
    expect(result.state.specWorkflows.map((entry) => entry.chatId)).toEqual([100]);
    expect(result.removedSessions).toBe(1);
    expect(result.removedApprovals).toBe(1);
  });
});
